apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-label-checker
  namespace: default
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes, use https://crontab-generator.org to generate 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: label-checker
              image: ***
              imagePullPolicy: Always
              env:
                - name: WEBHOOK_URL
                  value: "https://example.com/webhook"
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace 
                - name: LABELS_TO_CHECK
                  value: '[{"label_key": "observable", "label_value": "false"}]' # Can provide a list of labels
              resources:
                limits:
                  memory: "128Mi"
                  cpu: "500m"
                requests:
                  memory: "64Mi"
                  cpu: "250m"
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                allowPrivilegeEscalation: false
          restartPolicy: OnFailure
      backoffLimit: 3
