apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-label-checker
  namespace: mgmt
spec:
  schedule: "*/2 * * * *" # Runs every 2 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: mgmt-service-account  
          containers:
            - name: label-checker
              image: abstractlabs/cap-observability-cronjob
              imagePullPolicy: Always
              env:
                - name: DYNATRACE_API_URL
                  value: "https://****.live.dynatrace.com"
                - name: DYNATRACE_API_TOKEN
                  value: abc123
                - name: POD_NAMESPACES
                  value: "mgmt,test1,test2" # Comma-separated list of namespaces
                - name: LABELS_TO_CHECK
                  value: '[{"label_key": "observability", "label_value": "false"}]'
              securityContext:
                allowPrivilegeEscalation: false
          restartPolicy: OnFailure
      backoffLimit: 3
