apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mgmt-service-account-clusterrole-binding
subjects:
  - kind: ServiceAccount
    name: mgmt-service-account
    namespace: mgmt  
roleRef:
  kind: ClusterRole
  name: mgmt-service-account-clusterrole  
  apiGroup: rbac.authorization.k8s.io
