apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-info-reader-binding
subjects:
  - kind: ServiceAccount
    name: pod-info-reader-sa
    namespace: cronjob-name-space  
roleRef:
  kind: ClusterRole
  name: pod-info-reader  
  apiGroup: rbac.authorization.k8s.io
